# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body2(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, training_id: str=None, training_name: str=None, training_class: str=None, skill_class: str=None, it_level: str=None, summary: str=None, recruitment_num: str=None, participation_num: str=None, remarks: str=None, start_date: str=None, end_date: str=None, num_of_times: str=None, time_per_session: str=None, new_training_flg: str=None, selection_flg: str=None, conditions: str=None, company: str=None, teacher: str=None):  # noqa: E501
        """Body2 - a model defined in Swagger

        :param training_id: The training_id of this Body2.  # noqa: E501
        :type training_id: str
        :param training_name: The training_name of this Body2.  # noqa: E501
        :type training_name: str
        :param training_class: The training_class of this Body2.  # noqa: E501
        :type training_class: str
        :param skill_class: The skill_class of this Body2.  # noqa: E501
        :type skill_class: str
        :param it_level: The it_level of this Body2.  # noqa: E501
        :type it_level: str
        :param summary: The summary of this Body2.  # noqa: E501
        :type summary: str
        :param recruitment_num: The recruitment_num of this Body2.  # noqa: E501
        :type recruitment_num: str
        :param participation_num: The participation_num of this Body2.  # noqa: E501
        :type participation_num: str
        :param remarks: The remarks of this Body2.  # noqa: E501
        :type remarks: str
        :param start_date: The start_date of this Body2.  # noqa: E501
        :type start_date: str
        :param end_date: The end_date of this Body2.  # noqa: E501
        :type end_date: str
        :param num_of_times: The num_of_times of this Body2.  # noqa: E501
        :type num_of_times: str
        :param time_per_session: The time_per_session of this Body2.  # noqa: E501
        :type time_per_session: str
        :param new_training_flg: The new_training_flg of this Body2.  # noqa: E501
        :type new_training_flg: str
        :param selection_flg: The selection_flg of this Body2.  # noqa: E501
        :type selection_flg: str
        :param conditions: The conditions of this Body2.  # noqa: E501
        :type conditions: str
        :param company: The company of this Body2.  # noqa: E501
        :type company: str
        :param teacher: The teacher of this Body2.  # noqa: E501
        :type teacher: str
        """
        self.swagger_types = {
            'training_id': str,
            'training_name': str,
            'training_class': str,
            'skill_class': str,
            'it_level': str,
            'summary': str,
            'recruitment_num': str,
            'participation_num': str,
            'remarks': str,
            'start_date': str,
            'end_date': str,
            'num_of_times': str,
            'time_per_session': str,
            'new_training_flg': str,
            'selection_flg': str,
            'conditions': str,
            'company': str,
            'teacher': str
        }

        self.attribute_map = {
            'training_id': 'trainingId',
            'training_name': 'trainingName',
            'training_class': 'trainingClass',
            'skill_class': 'skillClass',
            'it_level': 'ITLevel',
            'summary': 'summary',
            'recruitment_num': 'recruitmentNum',
            'participation_num': 'participationNum',
            'remarks': 'remarks',
            'start_date': 'startDate',
            'end_date': 'endDate',
            'num_of_times': 'numOfTimes',
            'time_per_session': 'timePerSession',
            'new_training_flg': 'newTrainingFlg',
            'selection_flg': 'selectionFlg',
            'conditions': 'conditions',
            'company': 'company',
            'teacher': 'teacher'
        }
        self._training_id = training_id
        self._training_name = training_name
        self._training_class = training_class
        self._skill_class = skill_class
        self._it_level = it_level
        self._summary = summary
        self._recruitment_num = recruitment_num
        self._participation_num = participation_num
        self._remarks = remarks
        self._start_date = start_date
        self._end_date = end_date
        self._num_of_times = num_of_times
        self._time_per_session = time_per_session
        self._new_training_flg = new_training_flg
        self._selection_flg = selection_flg
        self._conditions = conditions
        self._company = company
        self._teacher = teacher

    @classmethod
    def from_dict(cls, dikt) -> 'Body2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_2 of this Body2.  # noqa: E501
        :rtype: Body2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def training_id(self) -> str:
        """Gets the training_id of this Body2.


        :return: The training_id of this Body2.
        :rtype: str
        """
        return self._training_id

    @training_id.setter
    def training_id(self, training_id: str):
        """Sets the training_id of this Body2.


        :param training_id: The training_id of this Body2.
        :type training_id: str
        """

        self._training_id = training_id

    @property
    def training_name(self) -> str:
        """Gets the training_name of this Body2.


        :return: The training_name of this Body2.
        :rtype: str
        """
        return self._training_name

    @training_name.setter
    def training_name(self, training_name: str):
        """Sets the training_name of this Body2.


        :param training_name: The training_name of this Body2.
        :type training_name: str
        """

        self._training_name = training_name

    @property
    def training_class(self) -> str:
        """Gets the training_class of this Body2.


        :return: The training_class of this Body2.
        :rtype: str
        """
        return self._training_class

    @training_class.setter
    def training_class(self, training_class: str):
        """Sets the training_class of this Body2.


        :param training_class: The training_class of this Body2.
        :type training_class: str
        """

        self._training_class = training_class

    @property
    def skill_class(self) -> str:
        """Gets the skill_class of this Body2.


        :return: The skill_class of this Body2.
        :rtype: str
        """
        return self._skill_class

    @skill_class.setter
    def skill_class(self, skill_class: str):
        """Sets the skill_class of this Body2.


        :param skill_class: The skill_class of this Body2.
        :type skill_class: str
        """

        self._skill_class = skill_class

    @property
    def it_level(self) -> str:
        """Gets the it_level of this Body2.


        :return: The it_level of this Body2.
        :rtype: str
        """
        return self._it_level

    @it_level.setter
    def it_level(self, it_level: str):
        """Sets the it_level of this Body2.


        :param it_level: The it_level of this Body2.
        :type it_level: str
        """

        self._it_level = it_level

    @property
    def summary(self) -> str:
        """Gets the summary of this Body2.


        :return: The summary of this Body2.
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary: str):
        """Sets the summary of this Body2.


        :param summary: The summary of this Body2.
        :type summary: str
        """

        self._summary = summary

    @property
    def recruitment_num(self) -> str:
        """Gets the recruitment_num of this Body2.


        :return: The recruitment_num of this Body2.
        :rtype: str
        """
        return self._recruitment_num

    @recruitment_num.setter
    def recruitment_num(self, recruitment_num: str):
        """Sets the recruitment_num of this Body2.


        :param recruitment_num: The recruitment_num of this Body2.
        :type recruitment_num: str
        """

        self._recruitment_num = recruitment_num

    @property
    def participation_num(self) -> str:
        """Gets the participation_num of this Body2.


        :return: The participation_num of this Body2.
        :rtype: str
        """
        return self._participation_num

    @participation_num.setter
    def participation_num(self, participation_num: str):
        """Sets the participation_num of this Body2.


        :param participation_num: The participation_num of this Body2.
        :type participation_num: str
        """

        self._participation_num = participation_num

    @property
    def remarks(self) -> str:
        """Gets the remarks of this Body2.


        :return: The remarks of this Body2.
        :rtype: str
        """
        return self._remarks

    @remarks.setter
    def remarks(self, remarks: str):
        """Sets the remarks of this Body2.


        :param remarks: The remarks of this Body2.
        :type remarks: str
        """

        self._remarks = remarks

    @property
    def start_date(self) -> str:
        """Gets the start_date of this Body2.


        :return: The start_date of this Body2.
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: str):
        """Sets the start_date of this Body2.


        :param start_date: The start_date of this Body2.
        :type start_date: str
        """

        self._start_date = start_date

    @property
    def end_date(self) -> str:
        """Gets the end_date of this Body2.


        :return: The end_date of this Body2.
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: str):
        """Sets the end_date of this Body2.


        :param end_date: The end_date of this Body2.
        :type end_date: str
        """

        self._end_date = end_date

    @property
    def num_of_times(self) -> str:
        """Gets the num_of_times of this Body2.


        :return: The num_of_times of this Body2.
        :rtype: str
        """
        return self._num_of_times

    @num_of_times.setter
    def num_of_times(self, num_of_times: str):
        """Sets the num_of_times of this Body2.


        :param num_of_times: The num_of_times of this Body2.
        :type num_of_times: str
        """

        self._num_of_times = num_of_times

    @property
    def time_per_session(self) -> str:
        """Gets the time_per_session of this Body2.


        :return: The time_per_session of this Body2.
        :rtype: str
        """
        return self._time_per_session

    @time_per_session.setter
    def time_per_session(self, time_per_session: str):
        """Sets the time_per_session of this Body2.


        :param time_per_session: The time_per_session of this Body2.
        :type time_per_session: str
        """

        self._time_per_session = time_per_session

    @property
    def new_training_flg(self) -> str:
        """Gets the new_training_flg of this Body2.


        :return: The new_training_flg of this Body2.
        :rtype: str
        """
        return self._new_training_flg

    @new_training_flg.setter
    def new_training_flg(self, new_training_flg: str):
        """Sets the new_training_flg of this Body2.


        :param new_training_flg: The new_training_flg of this Body2.
        :type new_training_flg: str
        """

        self._new_training_flg = new_training_flg

    @property
    def selection_flg(self) -> str:
        """Gets the selection_flg of this Body2.


        :return: The selection_flg of this Body2.
        :rtype: str
        """
        return self._selection_flg

    @selection_flg.setter
    def selection_flg(self, selection_flg: str):
        """Sets the selection_flg of this Body2.


        :param selection_flg: The selection_flg of this Body2.
        :type selection_flg: str
        """

        self._selection_flg = selection_flg

    @property
    def conditions(self) -> str:
        """Gets the conditions of this Body2.


        :return: The conditions of this Body2.
        :rtype: str
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions: str):
        """Sets the conditions of this Body2.


        :param conditions: The conditions of this Body2.
        :type conditions: str
        """

        self._conditions = conditions

    @property
    def company(self) -> str:
        """Gets the company of this Body2.


        :return: The company of this Body2.
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company: str):
        """Sets the company of this Body2.


        :param company: The company of this Body2.
        :type company: str
        """

        self._company = company

    @property
    def teacher(self) -> str:
        """Gets the teacher of this Body2.


        :return: The teacher of this Body2.
        :rtype: str
        """
        return self._teacher

    @teacher.setter
    def teacher(self, teacher: str):
        """Sets the teacher of this Body2.


        :param teacher: The teacher of this Body2.
        :type teacher: str
        """

        self._teacher = teacher
