# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EmployeeInfoEmployeesAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, company: str=None, mail_address: str=None):  # noqa: E501
        """EmployeeInfoEmployeesAddress - a model defined in Swagger

        :param company: The company of this EmployeeInfoEmployeesAddress.  # noqa: E501
        :type company: str
        :param mail_address: The mail_address of this EmployeeInfoEmployeesAddress.  # noqa: E501
        :type mail_address: str
        """
        self.swagger_types = {
            'company': str,
            'mail_address': str
        }

        self.attribute_map = {
            'company': 'company',
            'mail_address': 'mailAddress'
        }
        self._company = company
        self._mail_address = mail_address

    @classmethod
    def from_dict(cls, dikt) -> 'EmployeeInfoEmployeesAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmployeeInfo_employeesAddress of this EmployeeInfoEmployeesAddress.  # noqa: E501
        :rtype: EmployeeInfoEmployeesAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def company(self) -> str:
        """Gets the company of this EmployeeInfoEmployeesAddress.


        :return: The company of this EmployeeInfoEmployeesAddress.
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company: str):
        """Sets the company of this EmployeeInfoEmployeesAddress.


        :param company: The company of this EmployeeInfoEmployeesAddress.
        :type company: str
        """

        self._company = company

    @property
    def mail_address(self) -> str:
        """Gets the mail_address of this EmployeeInfoEmployeesAddress.


        :return: The mail_address of this EmployeeInfoEmployeesAddress.
        :rtype: str
        """
        return self._mail_address

    @mail_address.setter
    def mail_address(self, mail_address: str):
        """Sets the mail_address of this EmployeeInfoEmployeesAddress.


        :param mail_address: The mail_address of this EmployeeInfoEmployeesAddress.
        :type mail_address: str
        """

        self._mail_address = mail_address
