# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EmployeeInfoCertificationInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, certification_id: str=None, certification_name: str=None, summary: str=None, get_date: date=None):  # noqa: E501
        """EmployeeInfoCertificationInfo - a model defined in Swagger

        :param certification_id: The certification_id of this EmployeeInfoCertificationInfo.  # noqa: E501
        :type certification_id: str
        :param certification_name: The certification_name of this EmployeeInfoCertificationInfo.  # noqa: E501
        :type certification_name: str
        :param summary: The summary of this EmployeeInfoCertificationInfo.  # noqa: E501
        :type summary: str
        :param get_date: The get_date of this EmployeeInfoCertificationInfo.  # noqa: E501
        :type get_date: date
        """
        self.swagger_types = {
            'certification_id': str,
            'certification_name': str,
            'summary': str,
            'get_date': date
        }

        self.attribute_map = {
            'certification_id': 'certificationId',
            'certification_name': 'certificationName',
            'summary': 'summary',
            'get_date': 'getDate'
        }
        self._certification_id = certification_id
        self._certification_name = certification_name
        self._summary = summary
        self._get_date = get_date

    @classmethod
    def from_dict(cls, dikt) -> 'EmployeeInfoCertificationInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmployeeInfo_certificationInfo of this EmployeeInfoCertificationInfo.  # noqa: E501
        :rtype: EmployeeInfoCertificationInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def certification_id(self) -> str:
        """Gets the certification_id of this EmployeeInfoCertificationInfo.


        :return: The certification_id of this EmployeeInfoCertificationInfo.
        :rtype: str
        """
        return self._certification_id

    @certification_id.setter
    def certification_id(self, certification_id: str):
        """Sets the certification_id of this EmployeeInfoCertificationInfo.


        :param certification_id: The certification_id of this EmployeeInfoCertificationInfo.
        :type certification_id: str
        """

        self._certification_id = certification_id

    @property
    def certification_name(self) -> str:
        """Gets the certification_name of this EmployeeInfoCertificationInfo.


        :return: The certification_name of this EmployeeInfoCertificationInfo.
        :rtype: str
        """
        return self._certification_name

    @certification_name.setter
    def certification_name(self, certification_name: str):
        """Sets the certification_name of this EmployeeInfoCertificationInfo.


        :param certification_name: The certification_name of this EmployeeInfoCertificationInfo.
        :type certification_name: str
        """

        self._certification_name = certification_name

    @property
    def summary(self) -> str:
        """Gets the summary of this EmployeeInfoCertificationInfo.


        :return: The summary of this EmployeeInfoCertificationInfo.
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary: str):
        """Sets the summary of this EmployeeInfoCertificationInfo.


        :param summary: The summary of this EmployeeInfoCertificationInfo.
        :type summary: str
        """

        self._summary = summary

    @property
    def get_date(self) -> date:
        """Gets the get_date of this EmployeeInfoCertificationInfo.


        :return: The get_date of this EmployeeInfoCertificationInfo.
        :rtype: date
        """
        return self._get_date

    @get_date.setter
    def get_date(self, get_date: date):
        """Sets the get_date of this EmployeeInfoCertificationInfo.


        :param get_date: The get_date of this EmployeeInfoCertificationInfo.
        :type get_date: date
        """

        self._get_date = get_date
