# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TrainingInfoTrainingInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, employee_id: str=None, employee_name: str=None, joining_year: date=None, title: str=None, grade: str=None, recruitment_class: str=None, gender: str=None, birthdate: str=None, satisfaction_score: float=None, attendance_state: str=None):  # noqa: E501
        """TrainingInfoTrainingInfo - a model defined in Swagger

        :param employee_id: The employee_id of this TrainingInfoTrainingInfo.  # noqa: E501
        :type employee_id: str
        :param employee_name: The employee_name of this TrainingInfoTrainingInfo.  # noqa: E501
        :type employee_name: str
        :param joining_year: The joining_year of this TrainingInfoTrainingInfo.  # noqa: E501
        :type joining_year: date
        :param title: The title of this TrainingInfoTrainingInfo.  # noqa: E501
        :type title: str
        :param grade: The grade of this TrainingInfoTrainingInfo.  # noqa: E501
        :type grade: str
        :param recruitment_class: The recruitment_class of this TrainingInfoTrainingInfo.  # noqa: E501
        :type recruitment_class: str
        :param gender: The gender of this TrainingInfoTrainingInfo.  # noqa: E501
        :type gender: str
        :param birthdate: The birthdate of this TrainingInfoTrainingInfo.  # noqa: E501
        :type birthdate: str
        :param satisfaction_score: The satisfaction_score of this TrainingInfoTrainingInfo.  # noqa: E501
        :type satisfaction_score: float
        :param attendance_state: The attendance_state of this TrainingInfoTrainingInfo.  # noqa: E501
        :type attendance_state: str
        """
        self.swagger_types = {
            'employee_id': str,
            'employee_name': str,
            'joining_year': date,
            'title': str,
            'grade': str,
            'recruitment_class': str,
            'gender': str,
            'birthdate': str,
            'satisfaction_score': float,
            'attendance_state': str
        }

        self.attribute_map = {
            'employee_id': 'employeeId',
            'employee_name': 'employeeName',
            'joining_year': 'joiningYear',
            'title': 'title',
            'grade': 'grade',
            'recruitment_class': 'recruitmentClass',
            'gender': 'gender',
            'birthdate': 'birthdate',
            'satisfaction_score': 'satisfaction_score',
            'attendance_state': 'attendance_state'
        }
        self._employee_id = employee_id
        self._employee_name = employee_name
        self._joining_year = joining_year
        self._title = title
        self._grade = grade
        self._recruitment_class = recruitment_class
        self._gender = gender
        self._birthdate = birthdate
        self._satisfaction_score = satisfaction_score
        self._attendance_state = attendance_state

    @classmethod
    def from_dict(cls, dikt) -> 'TrainingInfoTrainingInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrainingInfo_TrainingInfo of this TrainingInfoTrainingInfo.  # noqa: E501
        :rtype: TrainingInfoTrainingInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def employee_id(self) -> str:
        """Gets the employee_id of this TrainingInfoTrainingInfo.


        :return: The employee_id of this TrainingInfoTrainingInfo.
        :rtype: str
        """
        return self._employee_id

    @employee_id.setter
    def employee_id(self, employee_id: str):
        """Sets the employee_id of this TrainingInfoTrainingInfo.


        :param employee_id: The employee_id of this TrainingInfoTrainingInfo.
        :type employee_id: str
        """

        self._employee_id = employee_id

    @property
    def employee_name(self) -> str:
        """Gets the employee_name of this TrainingInfoTrainingInfo.


        :return: The employee_name of this TrainingInfoTrainingInfo.
        :rtype: str
        """
        return self._employee_name

    @employee_name.setter
    def employee_name(self, employee_name: str):
        """Sets the employee_name of this TrainingInfoTrainingInfo.


        :param employee_name: The employee_name of this TrainingInfoTrainingInfo.
        :type employee_name: str
        """

        self._employee_name = employee_name

    @property
    def joining_year(self) -> date:
        """Gets the joining_year of this TrainingInfoTrainingInfo.


        :return: The joining_year of this TrainingInfoTrainingInfo.
        :rtype: date
        """
        return self._joining_year

    @joining_year.setter
    def joining_year(self, joining_year: date):
        """Sets the joining_year of this TrainingInfoTrainingInfo.


        :param joining_year: The joining_year of this TrainingInfoTrainingInfo.
        :type joining_year: date
        """

        self._joining_year = joining_year

    @property
    def title(self) -> str:
        """Gets the title of this TrainingInfoTrainingInfo.


        :return: The title of this TrainingInfoTrainingInfo.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this TrainingInfoTrainingInfo.


        :param title: The title of this TrainingInfoTrainingInfo.
        :type title: str
        """

        self._title = title

    @property
    def grade(self) -> str:
        """Gets the grade of this TrainingInfoTrainingInfo.


        :return: The grade of this TrainingInfoTrainingInfo.
        :rtype: str
        """
        return self._grade

    @grade.setter
    def grade(self, grade: str):
        """Sets the grade of this TrainingInfoTrainingInfo.


        :param grade: The grade of this TrainingInfoTrainingInfo.
        :type grade: str
        """

        self._grade = grade

    @property
    def recruitment_class(self) -> str:
        """Gets the recruitment_class of this TrainingInfoTrainingInfo.


        :return: The recruitment_class of this TrainingInfoTrainingInfo.
        :rtype: str
        """
        return self._recruitment_class

    @recruitment_class.setter
    def recruitment_class(self, recruitment_class: str):
        """Sets the recruitment_class of this TrainingInfoTrainingInfo.


        :param recruitment_class: The recruitment_class of this TrainingInfoTrainingInfo.
        :type recruitment_class: str
        """

        self._recruitment_class = recruitment_class

    @property
    def gender(self) -> str:
        """Gets the gender of this TrainingInfoTrainingInfo.


        :return: The gender of this TrainingInfoTrainingInfo.
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender: str):
        """Sets the gender of this TrainingInfoTrainingInfo.


        :param gender: The gender of this TrainingInfoTrainingInfo.
        :type gender: str
        """

        self._gender = gender

    @property
    def birthdate(self) -> str:
        """Gets the birthdate of this TrainingInfoTrainingInfo.


        :return: The birthdate of this TrainingInfoTrainingInfo.
        :rtype: str
        """
        return self._birthdate

    @birthdate.setter
    def birthdate(self, birthdate: str):
        """Sets the birthdate of this TrainingInfoTrainingInfo.


        :param birthdate: The birthdate of this TrainingInfoTrainingInfo.
        :type birthdate: str
        """

        self._birthdate = birthdate

    @property
    def satisfaction_score(self) -> float:
        """Gets the satisfaction_score of this TrainingInfoTrainingInfo.


        :return: The satisfaction_score of this TrainingInfoTrainingInfo.
        :rtype: float
        """
        return self._satisfaction_score

    @satisfaction_score.setter
    def satisfaction_score(self, satisfaction_score: float):
        """Sets the satisfaction_score of this TrainingInfoTrainingInfo.


        :param satisfaction_score: The satisfaction_score of this TrainingInfoTrainingInfo.
        :type satisfaction_score: float
        """

        self._satisfaction_score = satisfaction_score

    @property
    def attendance_state(self) -> str:
        """Gets the attendance_state of this TrainingInfoTrainingInfo.


        :return: The attendance_state of this TrainingInfoTrainingInfo.
        :rtype: str
        """
        return self._attendance_state

    @attendance_state.setter
    def attendance_state(self, attendance_state: str):
        """Sets the attendance_state of this TrainingInfoTrainingInfo.


        :param attendance_state: The attendance_state of this TrainingInfoTrainingInfo.
        :type attendance_state: str
        """

        self._attendance_state = attendance_state
